function surface = extract_reachability_surface(map_file, opts)
% EXTRACT_REACHABILITY_SURFACE  Convert voxel reachability map into a surface mesh.
%
%   surface = extract_reachability_surface(map_file) loads the reachability
%   grid contained in MAP_FILE (generated by build_reachability_map_FK.m),
%   produces a triangulated surface of the reachable volume, and saves the
%   result alongside useful metadata.
%
%   Name-value options:
%       output_mat      - Path to .mat file for the surface struct. Default:
%                         "<map_file>_surface.mat".
%       output_ply      - Optional ASCII PLY mesh export. Set to "" to skip.
%       reach_threshold - Occupancy threshold (0..1). Default: 0.5.
%       smooth_kernel   - Odd integer kernel size for smooth3() (0 to skip).
%       smooth_method   - 'box' (default) or 'gaussian' smoothing.
%       reduce_fraction - 0<r<=1 target fraction for reducepatch(). Default 0.35
%                         (65%% reduction). Set to 1 to keep full mesh.
%       min_cluster     - Minimum voxel count to keep a connected region.
%                         Requires Image Processing Toolbox. Default 32.
%       verbose         - Display progress messages (default true).
%
%   The returned SURFACE struct contains:
%       vertices  - (N x 3) double array of surface vertices in meters.
%       faces     - (M x 3) double array of 1-based triangle indices.
%       normals   - (N x 3) double array of per-vertex normals (unit length).
%       boundary_voxels - (K x 3) double array of voxel-centre coordinates.
%       meta      - struct with grid info, source file, timestamp, options.
%       stats     - struct with counts (voxels, faces, etc.).
%
%   Example
%   -------
%       surface = extract_reachability_surface('reach_map_mobile_mm_arm_only.mat', ...
%                  'output_ply', 'exports/reach_surface.ply');
%
%   The exported .mat surface file can be loaded from Python with:
%       import scipy.io
%       data = scipy.io.loadmat('reach_map_mobile_mm_arm_only_surface.mat')
%       vertices = data['surface']['vertices'][0,0]
%       faces = data['surface']['faces'][0,0] - 1    # convert to 0-based
%
%   If scipy.io is unavailable, the ASCII PLY export can be consumed via
%   trimesh, open3d, pyntcloud, MeshLab, Blender, etc.
%
%   See also: isosurface, smooth3, reducepatch, writematrix

arguments
    map_file (1,1) string
    opts.output_mat (1,1) string = "<auto>"
    opts.output_ply (1,1) string = ""
    opts.reach_threshold (1,1) double = 0.5
    opts.smooth_kernel (1,1) double {mustBeNonnegative} = 3
    opts.smooth_method (1,1) string = "box"
    opts.reduce_fraction (1,1) double {mustBePositive} = 0.35
    opts.min_cluster (1,1) double {mustBeNonnegative} = 32
    opts.verbose (1,1) logical = true
end

if ~isfile(map_file)
    error('extract_reachability_surface:FileNotFound', ...
          'Map file not found: %s', map_file);
end

save_mat = true;
if opts.output_mat == "<auto>"
    opts.output_mat = map_file + "_surface.mat";
elseif opts.output_mat == ""
    save_mat = false;
end

if opts.verbose
    fprintf('=== Reachability Surface Extraction ===\n');
    fprintf('Source: %s\n', map_file);
end

S = load(map_file, 'reachScore', 'config');
if ~isfield(S, 'reachScore')
    error('extract_reachability_surface:MissingField', ...
          'Variable "reachScore" not found in %s', map_file);
end
if ~isfield(S, 'config')
    error('extract_reachability_surface:MissingField', ...
          'Variable "config" not found in %s', map_file);
end

reachScore = S.reachScore;
config = S.config;
dims = size(reachScore);

if numel(dims) ~= 3
    error('extract_reachability_surface:InvalidShape', ...
          '"reachScore" must be a 3-D grid (got size %s)', mat2str(dims));
end

voxel = config.voxel_size;
if isscalar(voxel)
    voxel = [voxel voxel voxel];
end

origin = config.grid_origin;
grid_size = config.grid_size;
grid_dims = config.grid_dims;

if opts.verbose
    fprintf('Grid dims: [%d %d %d] voxels (voxel %.1f mm)\n', ...
            dims(1), dims(2), dims(3), voxel(1)*1000);
end

occupancy = reachScore >= opts.reach_threshold;

% Optional filtering of small disconnected pockets (requires bwconncomp)
if opts.min_cluster > 1
    if exist('bwconncomp', 'file') == 2
        cc = bwconncomp(occupancy, 6);
        num_voxels = cellfun(@numel, cc.PixelIdxList);
        small = find(num_voxels < opts.min_cluster);
        if ~isempty(small)
            occupancy(vertcat(cc.PixelIdxList{small})) = false;
            if opts.verbose
                fprintf('Removed %d small components (< %d voxels)\n', ...
                        numel(small), opts.min_cluster);
            end
        end
    elseif opts.verbose
        fprintf('Skipping cluster pruning (bwconncomp unavailable)\n');
    end
end

% Pre-smooth the binary volume to avoid jagged meshes
volume = double(occupancy);
if opts.smooth_kernel >= 3 && mod(opts.smooth_kernel, 2) == 1
    try
        volume = smooth3(volume, opts.smooth_method, opts.smooth_kernel);
        if opts.verbose
            fprintf('Applied smooth3 (%s, kernel %d)\n', ...
                    opts.smooth_method, opts.smooth_kernel);
        end
    catch ME
        warning('extract_reachability_surface:SmoothFailed', ...
                'smooth3 failed (%s). Continuing without smoothing.', ME.message);
        volume = double(occupancy);
    end
elseif opts.smooth_kernel ~= 0 && opts.verbose
    fprintf('Skipping smoothing (kernel must be odd integer >=3)\n');
end

% Cartesian coordinates for voxel centres
x = origin(1) + voxel(1) * ((0:dims(1)-1) + 0.5);
y = origin(2) + voxel(2) * ((0:dims(2)-1) + 0.5);
z = origin(3) + voxel(3) * ((0:dims(3)-1) + 0.5);
[X, Y, Z] = ndgrid(x, y, z);

fv = isosurface(X, Y, Z, volume, 0.5);
if isempty(fv.vertices)
    error('extract_reachability_surface:EmptySurface', ...
          'Isosurface extraction produced no vertices. Check threshold or input.');
end

if opts.reduce_fraction < 1
    target_fraction = min(max(opts.reduce_fraction, 0.01), 1); %#ok<MCSUP>
    fv = reducepatch(fv, target_fraction);
    if opts.verbose
        fprintf('reducepatch applied (fraction %.2f)\n', target_fraction);
    end
end

[gradX, gradY, gradZ] = gradient(volume, voxel(1), voxel(2), voxel(3));
Fx = griddedInterpolant({x, y, z}, gradX, 'linear', 'nearest');
Fy = griddedInterpolant({x, y, z}, gradY, 'linear', 'nearest');
Fz = griddedInterpolant({x, y, z}, gradZ, 'linear', 'nearest');

normals = -[ ...
    Fx(fv.vertices(:,1), fv.vertices(:,2), fv.vertices(:,3)), ...
    Fy(fv.vertices(:,1), fv.vertices(:,2), fv.vertices(:,3)), ...
    Fz(fv.vertices(:,1), fv.vertices(:,2), fv.vertices(:,3)) ...
    ];
normals = normalize_vectors(normals);

boundary_voxels = voxel_boundary_points(occupancy, origin, voxel);

timestamp = datetime('now', 'TimeZone', 'UTC');
timestamp.Format = "yyyy-MM-dd'T'HH:mm:ss'Z'";

surface = struct();
surface.vertices = fv.vertices;
surface.faces = fv.faces;
surface.normals = normals;
surface.boundary_voxels = boundary_voxels;
surface.meta = struct( ...
    'source_file', map_file, ...
    'grid_origin', origin, ...
    'grid_size', grid_size, ...
    'grid_dims', grid_dims, ...
    'voxel_size', voxel, ...
    'reach_threshold', opts.reach_threshold, ...
    'smooth_kernel', opts.smooth_kernel, ...
    'smooth_method', opts.smooth_method, ...
    'reduce_fraction', opts.reduce_fraction, ...
    'min_cluster', opts.min_cluster, ...
    'generated_at', string(timestamp) ...
    );

surface.stats = struct( ...
    'n_voxels', nnz(occupancy), ...
    'n_boundary_voxels', size(boundary_voxels, 1), ...
    'n_vertices', size(fv.vertices, 1), ...
    'n_faces', size(fv.faces, 1) ...
    );

if opts.verbose
    fprintf('Surface: %d vertices, %d faces\n', ...
            surface.stats.n_vertices, surface.stats.n_faces);
    fprintf('Boundary voxels (centres): %d\n', surface.stats.n_boundary_voxels);
end

if save_mat
    ensure_parent_folder(opts.output_mat);
    save(opts.output_mat, 'surface', '-v7');
    if opts.verbose
        info = dir(opts.output_mat);
        fprintf('Saved surface struct: %s (%.1f MB)\n', opts.output_mat, info.bytes/1e6);
    end
end

if opts.output_ply ~= ""
    ensure_parent_folder(opts.output_ply);
    write_ascii_ply(opts.output_ply, surface.vertices, surface.faces);
    if opts.verbose
        info = dir(opts.output_ply);
        fprintf('Saved mesh PLY: %s (%.1f MB)\n', opts.output_ply, info.bytes/1e6);
    end
end

if opts.verbose
    fprintf('=== Surface extraction complete ===\n');
end

end

% -------------------------------------------------------------------------
function normals = normalize_vectors(normals)
% Ensure normals have unit length; avoid division by zero.
len = sqrt(sum(normals.^2, 2));
len(len == 0) = 1;
normals = normals ./ len;
end

% -------------------------------------------------------------------------
function ensure_parent_folder(filepath)
[folder, ~, ~] = fileparts(filepath);
folder = string(folder);
if folder ~= "" && ~exist(folder, 'dir')
    mkdir(folder);
end
end

% -------------------------------------------------------------------------
function pts = voxel_boundary_points(occupancy, origin, voxel)
% Return centres of voxels that lie on the surface of the occupancy grid.
sz = size(occupancy);
neigh = zeros([sz 6], 'logical');

neigh(1:end-1,:, :,1) = occupancy(2:end,:,:);
neigh(:,1:end-1,:,2) = occupancy(:,2:end,:);
neigh(:,:,1:end-1,3) = occupancy(:,:,2:end);
neigh(2:end ,:, :,4) = occupancy(1:end-1,:,:);
neigh(:,2:end ,:,5) = occupancy(:,1:end-1,:);
neigh(:,:,2:end ,6) = occupancy(:,:,1:end-1);

is_boundary = occupancy & any(~neigh, 4);
idx = find(is_boundary);
[ix, iy, iz] = ind2sub(sz, idx);

x = origin(1) + voxel(1) * (ix - 0.5);
y = origin(2) + voxel(2) * (iy - 0.5);
z = origin(3) + voxel(3) * (iz - 0.5);
pts = [x(:), y(:), z(:)];
end

% -------------------------------------------------------------------------
function write_ascii_ply(filename, vertices, faces)
% Minimal ASCII PLY writer (triangular faces).
fid = fopen(filename, 'w');
if fid < 0
    error('extract_reachability_surface:IOError', ...
          'Failed to open %s for writing.', filename);
end
cleaner = onCleanup(@() fclose(fid));

nV = size(vertices, 1);
nF = size(faces, 1);

fprintf(fid, 'ply\n');
fprintf(fid, 'format ascii 1.0\n');
fprintf(fid, 'element vertex %d\n', nV);
fprintf(fid, 'property float x\n');
fprintf(fid, 'property float y\n');
fprintf(fid, 'property float z\n');
fprintf(fid, 'element face %d\n', nF);
fprintf(fid, 'property list uchar int vertex_indices\n');
fprintf(fid, 'end_header\n');

fprintf(fid, '%.6f %.6f %.6f\n', vertices');

faces_zero = faces - 1;
fprintf(fid, '3 %d %d %d\n', faces_zero');

end
