cd('C:/Users/yanbo/wSpace/cinebotRL/matlab');
addpath('tools');
extract_reachability_surface('reach_map_mobile_mm_arm_only.mat', ...
    'output_mat', 'exports/reach_surface.mat', ...
    'output_ply', 'exports/reach_surface.ply', ...
    'smooth_kernel', 3, ...
    'reduce_fraction', 0.4, ...
    'min_cluster', 16);
