#!/usr/bin/env python3
"""Generate trajectory curriculum manifests from the canonical dataset.

The generated manifests contain project-root-relative JSON paths. They are
consumed by MultiTrajectoryLoader without copying trajectory files.
"""

from __future__ import annotations

import argparse
import json
from dataclasses import dataclass
from pathlib import Path


@dataclass(frozen=True)
class TrajectoryStats:
    path: Path
    category: str
    length: int
    duration_s: float
    x_change: float
    y_change: float
    horizontal_displacement: float
    horizontal_range: float
    path_length: float

    @property
    def chassis_score(self) -> float:
        return max(self.x_change, self.horizontal_displacement, self.horizontal_range)


STAGE_BANDS = {
    "stage0_easy": (0.0, 1.0, 160),
    "stage1_recovery": (1.0, 2.2, 256),
    "stage2_moderate": (1.6, 2.8, 384),
    "stage3_full": (0.0, float("inf"), 0),
}


def load_stats(json_path: Path, waypoint_dt: float) -> TrajectoryStats | None:
    try:
        with open(json_path, "r", encoding="utf-8") as f:
            poses = json.load(f).get("poses", [])
    except Exception as exc:
        print(f"[WARN] Skipping {json_path}: {exc}")
        return None

    if not poses:
        return None

    positions = [pose["position"] for pose in poses]
    start = positions[0]
    end = positions[-1]
    x_vals = [p[0] for p in positions]
    y_vals = [p[1] for p in positions]

    path_length = 0.0
    for prev, curr in zip(positions, positions[1:]):
        dx = curr[0] - prev[0]
        dy = curr[1] - prev[1]
        dz = curr[2] - prev[2]
        path_length += (dx * dx + dy * dy + dz * dz) ** 0.5

    dx_total = end[0] - start[0]
    dy_total = end[1] - start[1]
    return TrajectoryStats(
        path=json_path,
        category=json_path.parent.name,
        length=len(poses),
        duration_s=len(poses) * waypoint_dt,
        x_change=abs(dx_total),
        y_change=abs(dy_total),
        horizontal_displacement=(dx_total * dx_total + dy_total * dy_total) ** 0.5,
        horizontal_range=((max(x_vals) - min(x_vals)) ** 2 + (max(y_vals) - min(y_vals)) ** 2) ** 0.5,
        path_length=path_length,
    )


def select_stage(stats: list[TrajectoryStats], stage: str) -> list[TrajectoryStats]:
    min_score, max_score, target_count = STAGE_BANDS[stage]
    selected = [s for s in stats if min_score <= s.chassis_score <= max_score]
    selected.sort(key=lambda s: (s.chassis_score, s.path_length, str(s.path)))

    if stage == "stage3_full" or target_count <= 0:
        return selected

    if len(selected) >= target_count:
        stride = max(1, len(selected) // target_count)
        selected = selected[::stride][:target_count]
    return selected


def write_manifest(project_root: Path, stage: str, selected: list[TrajectoryStats]) -> Path:
    stage_dir = project_root / "trajectoryToLearn" / stage
    stage_dir.mkdir(parents=True, exist_ok=True)
    manifest_path = stage_dir / "manifest.txt"

    with open(manifest_path, "w", encoding="utf-8") as f:
        f.write(f"# Generated by scripts/generate_stage_manifests.py for {stage}\n")
        f.write("# Paths are relative to the project root.\n")
        for item in selected:
            f.write(f"{item.path.relative_to(project_root).as_posix()}\n")
    return manifest_path


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--project-root", type=Path, default=Path.cwd())
    parser.add_argument("--trajectory-dir", type=Path, default=Path("trajectoryToLearn/world_json"))
    parser.add_argument("--stage", choices=sorted(STAGE_BANDS), default="stage1_recovery")
    parser.add_argument("--all-stages", action="store_true")
    parser.add_argument("--waypoint-dt", type=float, default=0.1)
    parser.add_argument("--min-duration", type=float, default=5.0)
    args = parser.parse_args()

    project_root = args.project_root.resolve()
    trajectory_dir = args.trajectory_dir
    if not trajectory_dir.is_absolute():
        trajectory_dir = project_root / trajectory_dir

    json_files = sorted(p for p in trajectory_dir.rglob("*.json") if "__MACOSX" not in str(p))
    stats = []
    for json_file in json_files:
        item = load_stats(json_file, args.waypoint_dt)
        if item is not None and item.duration_s >= args.min_duration:
            stats.append(item)

    if not stats:
        raise SystemExit(f"No trajectories found in {trajectory_dir} after duration filtering")

    stages = sorted(STAGE_BANDS) if args.all_stages else [args.stage]
    for stage in stages:
        selected = select_stage(stats, stage)
        if not selected:
            raise SystemExit(f"No trajectories selected for {stage}")
        manifest_path = write_manifest(project_root, stage, selected)
        scores = [s.chassis_score for s in selected]
        durations = [s.duration_s for s in selected]
        print(
            f"{stage}: wrote {len(selected)} trajectories to {manifest_path} "
            f"(score {min(scores):.2f}-{max(scores):.2f}m, "
            f"duration {min(durations):.1f}-{max(durations):.1f}s)"
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
