#!/usr/bin/env python3
"""Generate fixed-base micro trajectories for the first Proto2 Stage A gate.

The generated paths intentionally stay close to a known reachable reset target
used by the current stage0_easy set. They are not cinematic trajectories; they
are a diagnostic/learning curriculum for arm and gimbal tracking with the base
frozen.
"""

from __future__ import annotations

import argparse
import json
import math
from dataclasses import dataclass
from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_STAGE = "stage0_fixedbase_micro"
DEFAULT_CENTER = (1.05, 0.08, 0.86)
DEFAULT_ORIENTATION_XYZW = (0.5, -0.5, 0.5, -0.5)


@dataclass(frozen=True)
class MicroSpec:
    name: str
    x_amp: float
    y_amp: float
    z_amp: float
    phase: float
    mode: str


def _make_pose(x: float, y: float, z: float) -> dict[str, list[float]]:
    return {
        "position": [round(x, 6), round(y, 6), round(z, 6)],
        "orientation": [round(v, 6) for v in DEFAULT_ORIENTATION_XYZW],
    }


def _position(spec: MicroSpec, t: float, center: tuple[float, float, float]) -> tuple[float, float, float]:
    cx, cy, cz = center
    theta = 2.0 * math.pi * t + spec.phase

    if spec.mode == "hold":
        return cx, cy, cz
    if spec.mode == "x_line":
        return cx + spec.x_amp * math.sin(theta), cy, cz
    if spec.mode == "y_line":
        return cx, cy + spec.y_amp * math.sin(theta), cz
    if spec.mode == "z_line":
        return cx, cy, cz + spec.z_amp * math.sin(theta)
    if spec.mode == "xy_oval":
        return cx + spec.x_amp * math.sin(theta), cy + spec.y_amp * math.cos(theta), cz
    if spec.mode == "xyz_oval":
        return (
            cx + spec.x_amp * math.sin(theta),
            cy + spec.y_amp * math.cos(theta),
            cz + spec.z_amp * math.sin(theta + math.pi / 2.0),
        )
    if spec.mode == "figure8":
        return (
            cx + spec.x_amp * math.sin(theta),
            cy + spec.y_amp * math.sin(theta) * math.cos(theta),
            cz + spec.z_amp * math.sin(theta + math.pi / 3.0),
        )
    raise ValueError(f"Unsupported micro trajectory mode: {spec.mode}")


def build_specs() -> list[MicroSpec]:
    specs: list[MicroSpec] = [
        MicroSpec("hold_center", 0.0, 0.0, 0.0, 0.0, "hold"),
    ]
    modes = ["x_line", "y_line", "z_line", "xy_oval", "xyz_oval", "figure8"]
    amplitudes = [
        (0.035, 0.020, 0.020),
        (0.055, 0.030, 0.030),
        (0.075, 0.040, 0.040),
        (0.095, 0.050, 0.050),
    ]
    for amp_idx, (x_amp, y_amp, z_amp) in enumerate(amplitudes, start=1):
        for mode_idx, mode in enumerate(modes):
            phase = (mode_idx * math.pi / 5.0) + (amp_idx * math.pi / 11.0)
            specs.append(
                MicroSpec(
                    name=f"{mode}_a{amp_idx}",
                    x_amp=x_amp,
                    y_amp=y_amp,
                    z_amp=z_amp,
                    phase=phase,
                    mode=mode,
                )
            )
    return specs


def write_stage(
    project_root: Path,
    stage: str,
    center: tuple[float, float, float],
    num_waypoints: int,
) -> tuple[Path, int]:
    stage_dir = project_root / "trajectoryToLearn" / stage
    data_dir = stage_dir / "generated"
    data_dir.mkdir(parents=True, exist_ok=True)

    specs = build_specs()
    manifest_lines = [
        f"# Generated by scripts/generate_fixedbase_micro_stage.py for {stage}",
        "# Paths are relative to the project root.",
    ]

    for idx, spec in enumerate(specs):
        poses = []
        for step in range(num_waypoints):
            t = step / max(num_waypoints - 1, 1)
            poses.append(_make_pose(*_position(spec, t, center)))
        path = data_dir / f"{idx:03d}_{spec.name}.json"
        path.write_text(json.dumps({"poses": poses}, indent=2) + "\n", encoding="utf-8")
        manifest_lines.append(path.relative_to(project_root).as_posix())

    manifest_path = stage_dir / "manifest.txt"
    manifest_path.write_text("\n".join(manifest_lines) + "\n", encoding="utf-8")

    readme = stage_dir / "README.md"
    readme.write_text(
        "\n".join(
            [
                "# stage0_fixedbase_micro",
                "",
                "Purpose: first Stage A curriculum for arm/gimbal tracking with base actions frozen.",
                "",
                f"- trajectories: {len(specs)}",
                f"- waypoints per trajectory: {num_waypoints}",
                "- waypoint dt in loader: 0.1 s",
                f"- nominal duration: {num_waypoints * 0.1:.1f} s",
                f"- center: [{center[0]:.3f}, {center[1]:.3f}, {center[2]:.3f}]",
                "- max local amplitudes: x=0.095 m, y=0.050 m, z=0.050 m",
                "- orientation: constant xyzw [0.5, -0.5, 0.5, -0.5]",
                "",
                "This stage is deliberately not cinematic. It tests whether the policy can learn",
                "reachable fixed-base EE tracking before base-motion curricula are reintroduced.",
                "",
            ]
        ),
        encoding="utf-8",
    )
    return manifest_path, len(specs)


def parse_center(raw: str) -> tuple[float, float, float]:
    values = [float(part.strip()) for part in raw.split(",")]
    if len(values) != 3:
        raise argparse.ArgumentTypeError("--center must contain exactly three comma-separated floats")
    return values[0], values[1], values[2]


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--project-root", type=Path, default=PROJECT_ROOT)
    parser.add_argument("--stage", default=DEFAULT_STAGE)
    parser.add_argument("--center", type=parse_center, default=DEFAULT_CENTER)
    parser.add_argument("--num-waypoints", type=int, default=60)
    args = parser.parse_args()

    if args.num_waypoints < 50:
        raise SystemExit("--num-waypoints must be >= 50 so the stage passes min_trajectory_duration=5.0")

    project_root = args.project_root.resolve()
    manifest, count = write_stage(project_root, args.stage, args.center, args.num_waypoints)
    print(f"Wrote {count} fixed-base micro trajectories")
    print(f"Manifest: {manifest}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
