"""Thorough investigation of chassis movement during evaluation.

This script will systematically check:
1. Are chassis actions being generated by the policy?
2. Are chassis joint targets being set correctly?
3. Are chassis joints responding to commands?
4. Are trajectories actually being loaded?
"""

import argparse
import sys
from pathlib import Path
import torch
import numpy as np

SCRIPT_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = SCRIPT_DIR.parent.parent.parent
sys.path.insert(0, str(PROJECT_ROOT))
sys.path.insert(0, str(PROJECT_ROOT / "src"))

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--checkpoint", type=str, required=True)
    parser.add_argument("--num_envs", type=int, default=1)
    parser.add_argument("--steps", type=int, default=100)
    args = parser.parse_args()
    
    print("="*80)
    print("CHASSIS MOVEMENT INVESTIGATION")
    print("="*80)
    
    # Initialize Isaac Sim
    print("\n[1/4] Initializing Isaac Sim...")
    from isaaclab.app import AppLauncher
    app_launcher = AppLauncher(headless=False)  # Use GUI to see robot
    simulation_app = app_launcher.app
    
    import gymnasium as gym
    from stable_baselines3 import PPO
    
    # Register tasks
    print("[2/4] Registering tasks...")
    from task_spec import register_isaac_lab_tasks
    register_isaac_lab_tasks()
    
    # Create environment
    print("[3/4] Creating environment...")
    env = gym.make(
        "MobileMMTrackEE-v0",
        num_envs=args.num_envs,
        headless=False,
        trajectory_type="multi_recorded",
        use_all_trajectories=True,
    )
    
    # Load model
    print("[4/4] Loading model...")
    model = PPO.load(args.checkpoint, device="cuda")
    
    print("\n" + "="*80)
    print("RUNNING INVESTIGATION...")
    print("="*80)
    
    # Reset environment
    obs = env.reset()
    if isinstance(obs, tuple):
        obs, _ = obs
    if isinstance(obs, dict):
        obs = obs.get("policy", list(obs.values())[0])
    if hasattr(obs, 'cpu'):
        obs = obs.cpu().numpy()
    
    # Track data
    chassis_actions = []
    chassis_positions = []
    chassis_velocities = []
    ee_positions = []
    target_positions = []
    
    print(f"\nRunning {args.steps} steps and monitoring chassis movement...")
    print("="*80)
    
    for step in range(args.steps):
        # Get action from policy
        action, _ = model.predict(obs, deterministic=True)
        
        # Convert to torch
        actions_torch = torch.from_numpy(action).float().to("cuda:0")
        
        # Check what actions policy is outputting
        if step < 5 or step % 20 == 0:
            arm_actions = action[0, :6]
            chassis_vx = action[0, 6]
            chassis_wz = action[0, 7]
            print(f"\nStep {step}:")
            print(f"  Arm actions (6): {arm_actions}")
            print(f"  Chassis vx:      {chassis_vx:.4f}")
            print(f"  Chassis wz:      {chassis_wz:.4f}")
        
        # Store chassis actions
        chassis_actions.append(action[0, 6:8].copy())
        
        # Get current robot state BEFORE step
        unwrapped_env = env.unwrapped
        base_joint_ids = unwrapped_env._base_joint_ids if hasattr(unwrapped_env, '_base_joint_ids') else None
        
        if base_joint_ids is not None:
            base_pos = unwrapped_env.robot.data.joint_pos[0, base_joint_ids].cpu().numpy()
            base_vel = unwrapped_env.robot.data.joint_vel[0, base_joint_ids].cpu().numpy()
            chassis_positions.append(base_pos.copy())
            chassis_velocities.append(base_vel.copy())
            
            if step < 5 or step % 20 == 0:
                print(f"  Base position: x={base_pos[0]:.4f}, y={base_pos[1]:.4f}, theta={base_pos[2]:.4f}")
                print(f"  Base velocity: vx={base_vel[0]:.4f}, vy={base_vel[1]:.4f}, wz={base_vel[2]:.4f}")
        
        # Step environment
        result = unwrapped_env.step(actions_torch)
        
        if len(result) == 5:
            obs_dict, rewards, terminated, truncated, infos = result
        else:
            obs_dict, rewards, dones, infos = result
        
        # Get EE and target positions
        if hasattr(unwrapped_env, '_ee_body_idx'):
            ee_pos = unwrapped_env.robot.data.body_pos_w[0, unwrapped_env._ee_body_idx, :].cpu().numpy()
            ee_positions.append(ee_pos.copy())
        
        if hasattr(unwrapped_env, 'trajectory_manager'):
            target_pos, _ = unwrapped_env.trajectory_manager.get_target_pose()
            target_positions.append(target_pos[0].cpu().numpy().copy())
        
        # Convert observation for next step
        if isinstance(obs_dict, dict):
            obs_tensor = obs_dict.get("policy", list(obs_dict.values())[0])
            if hasattr(obs_tensor, 'cpu'):
                obs = obs_tensor.cpu().numpy()
            else:
                obs = np.array(obs_tensor)
        else:
            obs = obs_dict
    
    # Analysis
    print("\n" + "="*80)
    print("ANALYSIS RESULTS")
    print("="*80)
    
    chassis_actions = np.array(chassis_actions)
    chassis_positions = np.array(chassis_positions)
    chassis_velocities = np.array(chassis_velocities)
    
    print("\n1. CHASSIS ACTIONS FROM POLICY:")
    print(f"   vx range: [{chassis_actions[:, 0].min():.4f}, {chassis_actions[:, 0].max():.4f}]")
    print(f"   vx mean:  {chassis_actions[:, 0].mean():.4f} ± {chassis_actions[:, 0].std():.4f}")
    print(f"   vx non-zero: {np.sum(np.abs(chassis_actions[:, 0]) > 0.01)} / {len(chassis_actions)}")
    print(f"   wz range: [{chassis_actions[:, 1].min():.4f}, {chassis_actions[:, 1].max():.4f}]")
    print(f"   wz mean:  {chassis_actions[:, 1].mean():.4f} ± {chassis_actions[:, 1].std():.4f}")
    print(f"   wz non-zero: {np.sum(np.abs(chassis_actions[:, 1]) > 0.01)} / {len(chassis_actions)}")
    
    print("\n2. CHASSIS ACTUAL MOVEMENT:")
    pos_delta = chassis_positions[-1] - chassis_positions[0]
    print(f"   Total X displacement:     {pos_delta[0]:.4f} m")
    print(f"   Total Y displacement:     {pos_delta[1]:.4f} m")
    print(f"   Total Theta displacement: {pos_delta[2]:.4f} rad ({np.degrees(pos_delta[2]):.2f}°)")
    
    total_movement = np.sqrt(pos_delta[0]**2 + pos_delta[1]**2)
    print(f"   Total planar movement:    {total_movement:.4f} m")
    
    if total_movement < 0.01:
        print("   ⚠️  CHASSIS DID NOT MOVE! (<1cm)")
    elif total_movement < 0.1:
        print("   ⚠️  Chassis moved very little (<10cm)")
    else:
        print("   ✅ Chassis moved significantly")
    
    print("\n3. CHASSIS VELOCITY PROFILE:")
    print(f"   vx range: [{chassis_velocities[:, 0].min():.4f}, {chassis_velocities[:, 0].max():.4f}] m/s")
    print(f"   vx mean:  {chassis_velocities[:, 0].mean():.4f} ± {chassis_velocities[:, 0].std():.4f}")
    print(f"   wz range: [{chassis_velocities[:, 2].min():.4f}, {chassis_velocities[:, 2].max():.4f}] rad/s")
    print(f"   wz mean:  {chassis_velocities[:, 2].mean():.4f} ± {chassis_velocities[:, 2].std():.4f}")
    
    if len(ee_positions) > 0 and len(target_positions) > 0:
        ee_positions = np.array(ee_positions)
        target_positions = np.array(target_positions)
        tracking_errors = np.linalg.norm(ee_positions - target_positions, axis=1)
        
        print("\n4. END-EFFECTOR TRACKING:")
        print(f"   Mean tracking error: {tracking_errors.mean():.4f} m")
        print(f"   Min tracking error:  {tracking_errors.min():.4f} m")
        print(f"   Max tracking error:  {tracking_errors.max():.4f} m")
        
        target_movement = np.linalg.norm(target_positions[-1] - target_positions[0])
        print(f"\n5. TARGET TRAJECTORY:")
        print(f"   Total target movement: {target_movement:.4f} m")
        
        if target_movement < 0.1:
            print("   ⚠️  Target barely moved - might be using wrong trajectory type!")
    
    print("\n" + "="*80)
    print("DIAGNOSTIC CONCLUSION:")
    print("="*80)
    
    # Diagnose the issue
    policy_tries_to_move = np.mean(np.abs(chassis_actions[:, 0])) > 0.01 or np.mean(np.abs(chassis_actions[:, 1])) > 0.01
    robot_actually_moves = total_movement > 0.01
    
    if not policy_tries_to_move and not robot_actually_moves:
        print("❌ ISSUE: Policy outputs near-zero chassis actions")
        print("   -> Policy learned it doesn't need to move the base")
        print("   -> This could be because:")
        print("      1. Trajectories are all reachable without base movement")
        print("      2. Trajectory loading didn't work - using default circle/line")
        print("      3. Policy didn't receive chassis state as observations")
    elif policy_tries_to_move and not robot_actually_moves:
        print("❌ ISSUE: Policy commands chassis movement but robot doesn't respond")
        print("   -> Actuator configuration problem")
        print("   -> Joint limits too tight")
        print("   -> Stiffness/damping issue")
    elif not policy_tries_to_move and robot_actually_moves:
        print("⚠️  UNEXPECTED: Robot moves despite zero actions (drift?)")
    else:
        print("✅ Policy commands movement AND robot responds")
        print("   -> System working as expected")
    
    print("="*80)
    
    # Cleanup
    input("\nPress Enter to close...")
    env.close()
    simulation_app.close()

if __name__ == "__main__":
    main()
