#!/usr/bin/env python3
"""Compose validated FK stages into a mixed PPO curriculum stage."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
if hasattr(sys.stderr, "reconfigure"):
    sys.stderr.reconfigure(encoding="utf-8", errors="replace")

SCRIPT_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = SCRIPT_DIR.parent.parent


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--source_stages",
        nargs="+",
        default=["stage0_policy_envelope_fk_large08", "stage0_policy_envelope_fk_base025"],
        help="Stage names to interleave in order.",
    )
    parser.add_argument("--stage", default="stage0_policy_envelope_fk_mix_large08_base025")
    parser.add_argument(
        "--reward_source_stage",
        default="stage0_policy_envelope_fk_base025",
        help="Stage whose reset_config reward_overrides should be reused.",
    )
    return parser.parse_args()


def require(condition: bool, message: str) -> None:
    if not condition:
        raise RuntimeError(message)


def read_manifest(stage: str) -> list[str]:
    manifest = PROJECT_ROOT / "trajectoryToLearn" / stage / "manifest.txt"
    require(manifest.exists(), f"manifest not found: {manifest}")
    paths: list[str] = []
    for raw_line in manifest.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        require((PROJECT_ROOT / line).exists(), f"trajectory missing: {line}")
        paths.append(line)
    require(paths, f"stage has no manifest entries: {stage}")
    return paths


def load_reset(stage: str) -> dict:
    reset_path = PROJECT_ROOT / "trajectoryToLearn" / stage / "reset_config.json"
    require(reset_path.exists(), f"reset_config not found: {reset_path}")
    return json.loads(reset_path.read_text(encoding="utf-8"))


def main() -> int:
    args = parse_args()
    stage_dir = PROJECT_ROOT / "trajectoryToLearn" / args.stage
    stage_dir.mkdir(parents=True, exist_ok=True)

    manifest_lines = [
        f"# Generated by scripts/imitation/generate_policy_envelope_fk_mixed_stage.py for {args.stage}",
        "# Paths are relative to the project root.",
    ]
    counts = {}
    source_paths = []
    for source_stage in args.source_stages:
        paths = read_manifest(source_stage)
        counts[source_stage] = len(paths)
        source_paths.append((source_stage, paths))
        manifest_lines.append(f"# source_stage={source_stage} count={len(paths)}")

    max_count = max(len(paths) for _, paths in source_paths)
    for idx in range(max_count):
        for source_stage, paths in source_paths:
            if idx < len(paths):
                manifest_lines.append(f"# source_stage={source_stage} index={idx}")
                manifest_lines.append(paths[idx])

    reset_source = load_reset(args.reward_source_stage)
    reset_config = {
        "schema": "policy_envelope_fk_mixed_reset_config_v1",
        "source_stages": args.source_stages,
        "trajectory_counts": counts,
        "reward_source_stage": args.reward_source_stage,
        "reset_base_x_offset": reset_source["reset_base_x_offset"],
        "reset_base_y_offset": reset_source["reset_base_y_offset"],
        "source": "mixed manifest composition; trajectory files remain in source stages",
    }
    if "reward_overrides" in reset_source:
        reset_config["reward_overrides"] = reset_source["reward_overrides"]

    (stage_dir / "manifest.txt").write_text("\n".join(manifest_lines) + "\n", encoding="utf-8")
    (stage_dir / "reset_config.json").write_text(
        json.dumps(reset_config, indent=2) + "\n",
        encoding="utf-8",
    )
    print(f"[mixed-stage] wrote {stage_dir / 'manifest.txt'}")
    print(f"[mixed-stage] wrote {stage_dir / 'reset_config.json'}")
    print(f"[mixed-stage] counts={counts}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
